// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	video "video-tools/internal/handler/video"
	"video-tools/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/parse",
				Handler: video.ExtractVideoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/video"),
	)
}
